/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import FileController.FileData;
import Model.ThietBi;
import Model.ThietBiThucHanh;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author abccc
 */
public class DanhGiaThietBiThucHanhUser extends javax.swing.JFrame {

    /**
     * Creates new form DanhGiaThietBiThucHanhUser
     */
    public DanhGiaThietBiThucHanhUser() {
        initComponents();
    }
    FileData<ThietBi> iofile = new FileData<>();
    String filename = "Data.txt";
    List<ThietBi> dsTB = new ArrayList<>(iofile.readObjectFromFile(filename));
    static private String MaThietBi;
    DanhGiaThietBiThucHanhUser(String MaThietBi) {
        initComponents();
        this.MaThietBi = MaThietBi;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbBangDanhGiaThietBiThucHanh = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tbBangDanhGiaThietBiThucHanh.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "Tình Trạng Hoạt Động", null},
                {"2", "Điểm Tuổi Thọ", null},
                {"3", "Điểm Tiêu Hao", null},
                {"4", "Điểm Hiệu Suất", null},
                {"5", "Điểm Hư Hỏng", null},
                {"6", "Điểm Bảo Trì", null},
                {null, null, null}
            },
            new String [] {
                "STT", "Tiêu Chí Đánh Giá", "Điểm"
            }
        ));
        jScrollPane1.setViewportView(tbBangDanhGiaThietBiThucHanh);

        jButton1.setText("Đánh Giá");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Thoát");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("ĐÁNH GIÁ THIẾT BỊ THỰC HÀNH");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(jButton1)
                        .addGap(122, 122, 122)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(48, 48, 48))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        int columnIndex = 2;
        try {
            for (int i = 0; i < 6; i++) {
                Object value = tbBangDanhGiaThietBiThucHanh.getValueAt(i, columnIndex);

                if (value == null) {
                    JOptionPane.showMessageDialog(null, "Các điểm đánh giá phải được đánh giá hết!", "Thông báo", JOptionPane.WARNING_MESSAGE);
                    return;
                }
            }

            for (ThietBi x : dsTB) {
                if (x.getMaTb().equals(MaThietBi)) {
                    ((ThietBiThucHanh) x).setTinhTrangHoatDong(Short.parseShort(tbBangDanhGiaThietBiThucHanh.getValueAt(0, columnIndex).toString()));
                    ((ThietBiThucHanh) x).setDiemTuoiTho(Short.parseShort(tbBangDanhGiaThietBiThucHanh.getValueAt(1, columnIndex).toString()));
                    ((ThietBiThucHanh) x).setDiemTieuHao(Short.parseShort(tbBangDanhGiaThietBiThucHanh.getValueAt(2, columnIndex).toString()));
                    ((ThietBiThucHanh) x).setDiemHieuSuat(Short.parseShort(tbBangDanhGiaThietBiThucHanh.getValueAt(3, columnIndex).toString()));
                    ((ThietBiThucHanh) x).setDiemHuHong(Short.parseShort(tbBangDanhGiaThietBiThucHanh.getValueAt(4, columnIndex).toString()));
                    ((ThietBiThucHanh) x).setDiemBaoTri(Short.parseShort(tbBangDanhGiaThietBiThucHanh.getValueAt(5, columnIndex).toString()));
                }
            }

            iofile.WriteObjectToFile(dsTB, filename);
            JOptionPane.showMessageDialog(null, "Đánh giá thành công!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Điểm đánh giá phải là số nguyên hợp lệ!", "Thông báo", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        DanhGiaUser secondForm = new DanhGiaUser();
        secondForm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DanhGiaThietBiThucHanhUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DanhGiaThietBiThucHanhUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DanhGiaThietBiThucHanhUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DanhGiaThietBiThucHanhUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DanhGiaThietBiThucHanhUser(MaThietBi).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbBangDanhGiaThietBiThucHanh;
    // End of variables declaration//GEN-END:variables
}
